BAH-1305 | add path filter for triggering db backup
Co-authored-by: Soorya Kumaran C <sooryakumaran.c@thoughtworks.com>

diff --git a/.github/workflows/trigger.yml b/.github/workflows/trigger.yml
--- a/.github/workflows/trigger.yml
+++ b/.github/workflows/trigger.yml
@@ -3,6 +3,8 @@ on:
   push:
     branches:
       - master
+    paths:
+      - "demo/db-backups/**"
 
 env:
   ORG_NAME: Bahmni
@@ -14,17 +16,17 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        dependent-repos: ["odoo-modules","OpenElis"]
+        dependent-repos: ["odoo-modules", "OpenElis"]
     steps:
       - name: Create repository_dispatch
         env:
           REPOSITORY_NAME: ${{ matrix.dependent-repos }}
-        run : |
-              trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
-              if [ $trigger_result == 204 ];then
-                echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
-              else
-                echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
-                cat trigger_response.txt
-                exit 1
-              fi
+        run: |
+          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
+          if [ $trigger_result == 204 ];then
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+          else
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+            cat trigger_response.txt
+            exit 1
+          fi
